{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Correlation Analysis: Prelude to Calibration\n",
    "\n",
    "\n",
    "Correlation analysis, despite its simplicity and many shortcomings, remains a centerpiece of empirical analysis in many fields, particularly the paleosciences. Computing correlations is trivial enough; the difficulty lies in properly assessing their significance. Of particular importance are three considerations:\n",
    "\n",
    "- Persistence, which violates the standard assumption that the data are independent (which underlies the classical test of significance implemented, e.g. in Excel).\n",
    "- Time irregularities, for instance comparing two records with different time axes, possibly unevenly spaced (which standard software cannot deal with out of the box)\n",
    "- Age uncertainties for example comparing two records, each with an ensemble of plausible chronologies (generated, for instance, by a Bayesian age model)\n",
    "- Test multiplicity aka the \"Look Elsewhere effect\", which states that repeatedly performing the same test can result in unacceptably high type I error (accepting correlations as significant, when in fact they are not). This arises e.g. when correlating a paleoclimate record with an instrumental field, assessing significance at thounsands of grid points at once, or assessing significance within an age ensemble.\n",
    "\n",
    "Accordingly,  Pyleoclim facilitates an assessment of correlations that deals with all these cases, makes the necessary data transformations transparent to the user, and allows for one-line plot commands to visualize the results.\n",
    "\n",
    "In this notebook we reproduce the case of [Hu et al, 2017](http://dx.doi.org/10.1016/j.epsl.2016.11.048), particularly the example of their section 4, which illustrates several of these pitfalls at once.  The example uses the speleothem record of [McCabe-Glynn et al , 2013](https://www.nature.com/articles/ngeo1862). "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {
    "scrolled": false
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[autoreload of pandas._config.config failed: Traceback (most recent call last):\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 317, in update_class\n",
      "    update_instances(old, new)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 280, in update_instances\n",
      "    ref.__class__ = new\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/pandas/_config/config.py\", line 198, in __setattr__\n",
      "    raise OptionError(\"You can only set the value of existing options\")\n",
      "pandas._config.config.OptionError: 'You can only set the value of existing options'\n",
      "]\n",
      "[autoreload of pandas.core.nanops failed: Traceback (most recent call last):\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: nanstd() requires a code object with 2 free vars, not 4\n",
      "]\n",
      "[autoreload of pandas.core.arrays.boolean failed: Traceback (most recent call last):\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 302, in update_class\n",
      "    if update_generic(old_obj, new_obj): continue\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: __and___() requires a code object with 1 free vars, not 2\n",
      "]\n",
      "[autoreload of pandas.core.accessor failed: Traceback (most recent call last):\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 302, in update_class\n",
      "    if update_generic(old_obj, new_obj): continue\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: __dir__() requires a code object with 0 free vars, not 1\n",
      "]\n",
      "[autoreload of pandas.core.arrays.categorical failed: Traceback (most recent call last):\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 783, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/pandas/core/arrays/categorical.py\", line 56, in <module>\n",
      "    from pandas.core.strings.object_array import ObjectStringArrayMixin\n",
      "ModuleNotFoundError: No module named 'pandas.core.strings.object_array'; 'pandas.core.strings' is not a package\n",
      "]\n",
      "[autoreload of pandas.core.arrays.datetimelike failed: Traceback (most recent call last):\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 302, in update_class\n",
      "    if update_generic(old_obj, new_obj): continue\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: __getitem__() requires a code object with 0 free vars, not 1\n",
      "]\n",
      "[autoreload of pandas.core.arrays.integer failed: Traceback (most recent call last):\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 302, in update_class\n",
      "    if update_generic(old_obj, new_obj): continue\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: sum() requires a code object with 0 free vars, not 1\n",
      "]\n",
      "[autoreload of pandas.core.arrays.sparse.array failed: Traceback (most recent call last):\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 302, in update_class\n",
      "    if update_generic(old_obj, new_obj): continue\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: __pos__() requires a code object with 2 free vars, not 0\n",
      "]\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[autoreload of pandas.core.indexes.base failed: Traceback (most recent call last):\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 302, in update_class\n",
      "    if update_generic(old_obj, new_obj): continue\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: __add__() requires a code object with 0 free vars, not 2\n",
      "]\n",
      "[autoreload of pandas.core.arrays.interval failed: Traceback (most recent call last):\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 783, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/pandas/core/arrays/interval.py\", line 10, in <module>\n",
      "    from pandas._libs.interval import (\n",
      "ImportError: cannot import name 'VALID_CLOSED' from 'pandas._libs.interval' (/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/pandas/_libs/interval.cpython-38-darwin.so)\n",
      "]\n",
      "[autoreload of pandas.core.arrays.numpy_ failed: Traceback (most recent call last):\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 783, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/pandas/core/arrays/numpy_.py\", line 17, in <module>\n",
      "    from pandas.core.strings.object_array import ObjectStringArrayMixin\n",
      "ModuleNotFoundError: No module named 'pandas.core.strings.object_array'; 'pandas.core.strings' is not a package\n",
      "]\n",
      "[autoreload of pandas.core.arrays.string_ failed: Traceback (most recent call last):\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 783, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/pandas/core/arrays/string_.py\", line 21, in <module>\n",
      "    from pandas.core.arrays import FloatingArray, IntegerArray, PandasArray\n",
      "ImportError: cannot import name 'FloatingArray' from 'pandas.core.arrays' (/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/pandas/core/arrays/__init__.py)\n",
      "]\n",
      "[autoreload of pandas.core.indexes.category failed: Traceback (most recent call last):\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 302, in update_class\n",
      "    if update_generic(old_obj, new_obj): continue\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: duplicated() requires a code object with 0 free vars, not 1\n",
      "]\n",
      "[autoreload of pandas.core.indexes.numeric failed: Traceback (most recent call last):\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 302, in update_class\n",
      "    if update_generic(old_obj, new_obj): continue\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: __neg__() requires a code object with 1 free vars, not 0\n",
      "]\n",
      "[autoreload of pandas.core.indexes.datetimelike failed: Traceback (most recent call last):\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 302, in update_class\n",
      "    if update_generic(old_obj, new_obj): continue\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: delete() requires a code object with 0 free vars, not 1\n",
      "]\n",
      "[autoreload of pandas.core.indexes.datetimes failed: Traceback (most recent call last):\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 302, in update_class\n",
      "    if update_generic(old_obj, new_obj): continue\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: to_perioddelta() requires a code object with 2 free vars, not 0\n",
      "]\n",
      "[autoreload of pandas.core.indexes.multi failed: Traceback (most recent call last):\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 302, in update_class\n",
      "    if update_generic(old_obj, new_obj): continue\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 340, in <lambda>\n",
      "    lambda a, b: update_function(a.__func__, b.__func__)),\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: from_tuples() requires a code object with 0 free vars, not 1\n",
      "]\n",
      "[autoreload of pandas.core.indexes.timedeltas failed: Traceback (most recent call last):\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 302, in update_class\n",
      "    if update_generic(old_obj, new_obj): continue\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: all() requires a code object with 1 free vars, not 0\n",
      "]\n",
      "[autoreload of pandas.core.indexes.interval failed: Traceback (most recent call last):\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 302, in update_class\n",
      "    if update_generic(old_obj, new_obj): continue\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: func() requires a code object with 2 free vars, not 0\n",
      "]\n",
      "[autoreload of pandas.core.indexes.period failed: Traceback (most recent call last):\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 302, in update_class\n",
      "    if update_generic(old_obj, new_obj): continue\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: asof_locs() requires a code object with 0 free vars, not 1\n",
      "]\n",
      "[autoreload of pandas.core.indexes.range failed: Traceback (most recent call last):\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 302, in update_class\n",
      "    if update_generic(old_obj, new_obj): continue\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: intersection() requires a code object with 1 free vars, not 0\n",
      "]\n",
      "[autoreload of pandas.core.indexing failed: Traceback (most recent call last):\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 783, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/pandas/core/indexing.py\", line 9, in <module>\n",
      "    from pandas._libs.indexing import NDFrameIndexerBase\n",
      "ImportError: cannot import name 'NDFrameIndexerBase' from 'pandas._libs.indexing' (/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/pandas/_libs/indexing.cpython-38-darwin.so)\n",
      "]\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[autoreload of pandas.core.internals.blocks failed: Traceback (most recent call last):\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 302, in update_class\n",
      "    if update_generic(old_obj, new_obj): continue\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: __init__() requires a code object with 1 free vars, not 0\n",
      "]\n",
      "[autoreload of pandas.core.tools.datetimes failed: Traceback (most recent call last):\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 783, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/pandas/core/tools/datetimes.py\", line 29, in <module>\n",
      "    from pandas._libs.tslibs.parsing import (  # noqa\n",
      "ImportError: cannot import name 'format_is_iso' from 'pandas._libs.tslibs.parsing' (/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/pandas/_libs/tslibs/parsing.cpython-38-darwin.so)\n",
      "]\n",
      "[autoreload of pandas.core.window.rolling failed: Traceback (most recent call last):\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 783, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/pandas/core/window/rolling.py\", line 51, in <module>\n",
      "    from pandas.core.aggregation import aggregate\n",
      "ImportError: cannot import name 'aggregate' from 'pandas.core.aggregation' (/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/pandas/core/aggregation.py)\n",
      "]\n",
      "[autoreload of pandas.core.window.ewm failed: Traceback (most recent call last):\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 783, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/pandas/core/window/ewm.py\", line 30, in <module>\n",
      "    from pandas.core.window.rolling import BaseWindow, BaseWindowGroupby, dispatch\n",
      "ImportError: cannot import name 'BaseWindow' from 'pandas.core.window.rolling' (/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/pandas/core/window/rolling.py)\n",
      "]\n",
      "[autoreload of pandas.core.window.expanding failed: Traceback (most recent call last):\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 783, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/pandas/core/window/expanding.py\", line 12, in <module>\n",
      "    from pandas.core.window.rolling import BaseWindowGroupby, RollingAndExpandingMixin\n",
      "ImportError: cannot import name 'BaseWindowGroupby' from 'pandas.core.window.rolling' (/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/pandas/core/window/rolling.py)\n",
      "]\n",
      "[autoreload of pandas.core.window failed: Traceback (most recent call last):\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 783, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/pandas/core/window/__init__.py\", line 1, in <module>\n",
      "    from pandas.core.window.ewm import (  # noqa:F401\n",
      "ImportError: cannot import name 'ExponentialMovingWindowGroupby' from 'pandas.core.window.ewm' (/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/pandas/core/window/ewm.py)\n",
      "]\n",
      "[autoreload of pandas.core.series failed: Traceback (most recent call last):\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 783, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/pandas/core/series.py\", line 72, in <module>\n",
      "    from pandas.core.aggregation import aggregate, transform\n",
      "ImportError: cannot import name 'aggregate' from 'pandas.core.aggregation' (/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/pandas/core/aggregation.py)\n",
      "]\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[autoreload of pandas.core.frame failed: Traceback (most recent call last):\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 302, in update_class\n",
      "    if update_generic(old_obj, new_obj): continue\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: sort_index() requires a code object with 0 free vars, not 1\n",
      "]\n",
      "[autoreload of pandas.io.parsers failed: Traceback (most recent call last):\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 302, in update_class\n",
      "    if update_generic(old_obj, new_obj): continue\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: close() requires a code object with 0 free vars, not 1\n",
      "]\n",
      "[autoreload of pandas.io.excel._odfreader failed: Traceback (most recent call last):\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 783, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/pandas/io/excel/_odfreader.py\", line 10, in <module>\n",
      "    from pandas.io.excel._base import BaseExcelReader\n",
      "ImportError: cannot import name 'BaseExcelReader' from 'pandas.io.excel._base' (/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/pandas/io/excel/_base.py)\n",
      "]\n",
      "[autoreload of pandas.io.excel._openpyxl failed: Traceback (most recent call last):\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 783, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/pandas/io/excel/_openpyxl.py\", line 8, in <module>\n",
      "    from pandas.io.excel._base import BaseExcelReader, ExcelWriter\n",
      "ImportError: cannot import name 'BaseExcelReader' from 'pandas.io.excel._base' (/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/pandas/io/excel/_base.py)\n",
      "]\n",
      "[autoreload of pandas.io.excel._pyxlsb failed: Traceback (most recent call last):\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 783, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/pandas/io/excel/_pyxlsb.py\", line 6, in <module>\n",
      "    from pandas.io.excel._base import BaseExcelReader\n",
      "ImportError: cannot import name 'BaseExcelReader' from 'pandas.io.excel._base' (/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/pandas/io/excel/_base.py)\n",
      "]\n",
      "[autoreload of pandas.io.excel._xlrd failed: Traceback (most recent call last):\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 783, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/pandas/io/excel/_xlrd.py\", line 8, in <module>\n",
      "    from pandas.io.excel._base import BaseExcelReader\n",
      "ImportError: cannot import name 'BaseExcelReader' from 'pandas.io.excel._base' (/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/pandas/io/excel/_base.py)\n",
      "]\n",
      "[autoreload of pandas.io.excel._base failed: Traceback (most recent call last):\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 783, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/pandas/io/excel/_base.py\", line 973, in <module>\n",
      "    class ExcelFile:\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/pandas/io/excel/_base.py\", line 1018, in ExcelFile\n",
      "    from pandas.io.excel._odfreader import ODFReader\n",
      "ImportError: cannot import name 'ODFReader' from 'pandas.io.excel._odfreader' (/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/pandas/io/excel/_odfreader.py)\n",
      "]\n",
      "[autoreload of pandas.io.excel failed: Traceback (most recent call last):\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 783, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/pandas/io/excel/__init__.py\", line 3, in <module>\n",
      "    from pandas.io.excel._openpyxl import OpenpyxlWriter as _OpenpyxlWriter\n",
      "ImportError: cannot import name 'OpenpyxlWriter' from 'pandas.io.excel._openpyxl' (/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/pandas/io/excel/_openpyxl.py)\n",
      "]\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[autoreload of pandas._testing failed: Traceback (most recent call last):\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 783, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/pandas/_testing.py\", line 3054, in <module>\n",
      "    cython_table = pd.core.base.SelectionMixin._cython_table.items()\n",
      "AttributeError: module 'pandas.core' has no attribute 'base'\n",
      "]\n",
      "[autoreload of psutil._psosx failed: Traceback (most recent call last):\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 783, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/psutil/_psosx.py\", line 38, in <module>\n",
      "    PAGESIZE = cext_posix.getpagesize()\n",
      "AttributeError: module 'psutil._psutil_posix' has no attribute 'getpagesize'\n",
      "]\n",
      "[autoreload of psutil failed: Traceback (most recent call last):\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 783, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/psutil/__init__.py\", line 239, in <module>\n",
      "    raise ImportError(msg)\n",
      "ImportError: version conflict: '/Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/psutil/_psutil_osx.cpython-38-darwin.so' C extension module was built for another version of psutil (5.7.2 instead of 5.8.0); you may try to 'pip uninstall psutil', manually remove /Users/julieneg/opt/miniconda3/envs/pyleo/lib/python3.8/site-packages/psutil/_psutil_osx.cpython-38-darwin.so or clean the virtual env somehow, then reinstall\n",
      "]\n"
     ]
    }
   ],
   "source": [
    "%load_ext autoreload\n",
    "%autoreload 2\n",
    "    \n",
    "import pyleoclim as pyleo\n",
    "import numpy as np\n",
    "import xarray as xr"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "We first load SST data"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "url = 'https://psl.noaa.gov/thredds/dodsC/Datasets/noaa.ersst.v5/sst.mnmean.nc'\n",
    "with xr.open_d"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
